

stages:          # List of stages for jobs, and their order of execution
- build
- test
- deploy

build-job:       # This job runs in the build stage, which runs first.
   stage: build
   script: mvn compile
   

jacoco:
   stage: test
   script: mvn jacoco:prepare-agent package jacoco:report
   artifacts:
      paths:
      - parcer/target/site/jacoco
   only:
    - master
